# Generated by Django 3.2.9 on 2021-11-10 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='books',
            name='published_on',
        ),
    ]
